-- @tuples_reseau_tan.sql
spool tuples_reseau_tan.log

prompt *************************************************************
prompt ******************** DELETE TABLE *****************************
prompt *************************************************************

DELETE FROM RESEAUX;
DELETE FROM LIGNE;
DELETE FROM ARRET;
DELETE FROM VEHICULE;

prompt *************************************************************
prompt ******************** INSERT TUPLES **************************
prompt *************************************************************

--tuples dans la table ligne
INSERT INTO LIGNE VALUES (1,'Ligne 1','Rail');
INSERT INTO LIGNE VALUES (2,'Ligne 2','Rail');
INSERT INTO LIGNE VALUES (3,'C5','Route');
INSERT INTO LIGNE VALUES (4,'N1','Fluviales');
INSERT INTO LIGNE VALUES (5,'N3','Fluviales');
INSERT INTO LIGNE VALUES (6,'Ligne 4','Route');
INSERT INTO LIGNE VALUES (7,'N2','Fluviales');
INSERT INTO LIGNE VALUES (8,'Deplacement dedie','Route');
INSERT INTO LIGNE VALUES (9,'12','Route');
INSERT INTO LIGNE VALUES (10,'Ligne 5','Route');
INSERT INTO LIGNE VALUES (11, 'Ligne 6', 'Rail');
INSERT INTO LIGNE VALUES (12, 'Ligne 7', 'Rail');
INSERT INTO LIGNE VALUES (13, 'C6', 'Route');
INSERT INTO LIGNE VALUES (14, 'N4', 'Fluviales');
INSERT INTO LIGNE VALUES (15, 'N5', 'Fluviales');
INSERT INTO LIGNE VALUES (16, 'Ligne 8', 'Route');
INSERT INTO LIGNE VALUES (17, 'N6', 'Fluviales');
INSERT INTO LIGNE VALUES (18, 'Express 1', 'Route');
INSERT INTO LIGNE VALUES (19, '13', 'Route');
INSERT INTO LIGNE VALUES (20, 'Ligne 9', 'Route');
INSERT INTO LIGNE VALUES (21, 'Ligne 10', 'Rail');
INSERT INTO LIGNE VALUES (22, 'Ligne 11', 'Rail');
INSERT INTO LIGNE VALUES (23, 'C7', 'Route');
INSERT INTO LIGNE VALUES (24, 'N7', 'Fluviales');
INSERT INTO LIGNE VALUES (25, 'N8', 'Fluviales');
INSERT INTO LIGNE VALUES (26, 'Ligne 12', 'Route');
INSERT INTO LIGNE VALUES (27, 'N9', 'Fluviales');
INSERT INTO LIGNE VALUES (28, 'Express 2', 'Route');
INSERT INTO LIGNE VALUES (29, '14', 'Route');
INSERT INTO LIGNE VALUES (30, 'Ligne 13', 'Route');

--tuples dans la table arret
INSERT INTO ARRET VALUES (1,'Commerce');
INSERT INTO ARRET VALUES (2,'Beaujoire');
INSERT INTO ARRET VALUES (3,'Hôtel Dieu');
INSERT INTO ARRET VALUES (4,'Gare Maritime');
INSERT INTO ARRET VALUES (5,'Trentemoult');
INSERT INTO ARRET VALUES (6,'Gare Sud');
INSERT INTO ARRET VALUES (7,'Hôtel de Region');
INSERT INTO ARRET VALUES (8,'Île de Nantes');
INSERT INTO ARRET VALUES (9,'Universite');
INSERT INTO ARRET VALUES (10,'Hangar a Banane');
INSERT INTO ARRET VALUES (11, 'Pont Rousseau');
INSERT INTO ARRET VALUES (12, 'Chateau');
INSERT INTO ARRET VALUES (13, 'Erdre Active');
INSERT INTO ARRET VALUES (14, 'Pirmil');
INSERT INTO ARRET VALUES (15, 'Beaulieu');
INSERT INTO ARRET VALUES (16, 'Gare Nord');
INSERT INTO ARRET VALUES (17, 'Jules Verne');
INSERT INTO ARRET VALUES (18, 'Doulon');
INSERT INTO ARRET VALUES (19, 'Mairie de Rezé');
INSERT INTO ARRET VALUES (20, 'Les Couëts');
INSERT INTO ARRET VALUES (21, 'Chantenay');
INSERT INTO ARRET VALUES (22, 'Mellinet');
INSERT INTO ARRET VALUES (23, 'Dervallières');
INSERT INTO ARRET VALUES (24, 'Procé');
INSERT INTO ARRET VALUES (25, 'Hauts Pavés');
INSERT INTO ARRET VALUES (26, 'Sillon de Bretagne');
INSERT INTO ARRET VALUES (27, 'Sainte-Thérèse');
INSERT INTO ARRET VALUES (28, 'Jean Perrin');
INSERT INTO ARRET VALUES (29, 'Orvault Grand Val');
INSERT INTO ARRET VALUES (30, 'Petit Port');

--tuples dans la table vehicule
INSERT INTO VEHICULE VALUES (101,'Tramway',250,'electrique');
INSERT INTO VEHICULE VALUES (102,'Tramway',250,'electrique');
INSERT INTO VEHICULE VALUES (201,'Bus',50,'Gaz_Naturel');
INSERT INTO VEHICULE VALUES (202,'Bus',50,'Gaz_Naturel');
INSERT INTO VEHICULE VALUES (301,'Navibus',95,'Diesel');
INSERT INTO VEHICULE VALUES (302,'Navibus',95,'Hydrogene');
INSERT INTO VEHICULE VALUES (303,'Navibus',95,'electrique');
INSERT INTO VEHICULE VALUES (401,'BusWay',150,'electrique');
INSERT INTO VEHICULE VALUES (402,'BusWay',150,'electrique');
INSERT INTO VEHICULE VALUES (501,'ProxiTan',4,'Diesel');
INSERT INTO VEHICULE VALUES (502, 'Tramway', 250, 'electrique');
INSERT INTO VEHICULE VALUES (503, 'Tramway', 250, 'electrique');
INSERT INTO VEHICULE VALUES (601, 'Bus', 50, 'Gaz_Naturel');
INSERT INTO VEHICULE VALUES (602, 'Bus', 50, 'Gaz_Naturel');
INSERT INTO VEHICULE VALUES (701, 'Navibus', 95, 'Diesel');
INSERT INTO VEHICULE VALUES (702, 'Navibus', 95, 'Hydrogene');
INSERT INTO VEHICULE VALUES (703, 'Navibus', 95, 'electrique');
INSERT INTO VEHICULE VALUES (801, 'BusWay', 150, 'electrique');
INSERT INTO VEHICULE VALUES (802, 'BusWay', 150, 'electrique');
INSERT INTO VEHICULE VALUES (901, 'ProxiTan', 4, 'Diesel');
INSERT INTO VEHICULE VALUES (902, 'Tramway', 250, 'electrique');
INSERT INTO VEHICULE VALUES (903, 'Tramway', 250, 'electrique');
INSERT INTO VEHICULE VALUES (1001, 'Bus', 50, 'Gaz_Naturel');
INSERT INTO VEHICULE VALUES (1002, 'Bus', 50, 'Gaz_Naturel');
INSERT INTO VEHICULE VALUES (1101, 'Navibus', 95, 'Diesel');
INSERT INTO VEHICULE VALUES (1102, 'Navibus', 95, 'Hydrogene');
INSERT INTO VEHICULE VALUES (1103, 'Navibus', 95, 'electrique');
INSERT INTO VEHICULE VALUES (1201, 'BusWay', 150, 'electrique');
INSERT INTO VEHICULE VALUES (1202, 'BusWay', 150, 'electrique');

--tuples dans la table reseaux
INSERT INTO RESEAUX VALUES (1, 1, 101);
INSERT INTO RESEAUX VALUES (1, 3, 102);
INSERT INTO RESEAUX VALUES (2, 2, 102);
INSERT INTO RESEAUX VALUES (3, 3, 201);
INSERT INTO RESEAUX VALUES (4, 4, 301);
INSERT INTO RESEAUX VALUES (4, 5, 301);
INSERT INTO RESEAUX VALUES (5, 6, 302);
INSERT INTO RESEAUX VALUES (6, 7, 401);
INSERT INTO RESEAUX VALUES (7, 8, 303);
INSERT INTO RESEAUX VALUES (9, 9, 202);
INSERT INTO RESEAUX VALUES (10, 1, 402);
INSERT INTO RESEAUX VALUES (11, 11, 502);
INSERT INTO RESEAUX VALUES (12, 12, 503);
INSERT INTO RESEAUX VALUES (13, 13, 601);
INSERT INTO RESEAUX VALUES (14, 14, 701);
INSERT INTO RESEAUX VALUES (15, 15, 702);
INSERT INTO RESEAUX VALUES (16, 16, 703);
INSERT INTO RESEAUX VALUES (17, 17, 801);
INSERT INTO RESEAUX VALUES (18, 18, 802);
INSERT INTO RESEAUX VALUES (19, 19, 901);
INSERT INTO RESEAUX VALUES (20, 20, 902);
INSERT INTO RESEAUX VALUES (21, 21, 903);
INSERT INTO RESEAUX VALUES (22, 22, 1001);
INSERT INTO RESEAUX VALUES (23, 23, 1002);
INSERT INTO RESEAUX VALUES (24, 24, 1101);
INSERT INTO RESEAUX VALUES (25, 25, 1102);
INSERT INTO RESEAUX VALUES (26, 26, 1103);
INSERT INTO RESEAUX VALUES (27, 27, 1201);
INSERT INTO RESEAUX VALUES (28, 28, 1202);
INSERT INTO RESEAUX VALUES (29, 29, 501);
INSERT INTO RESEAUX VALUES (30, 30, 502);
